// Generated by CoffeeScript 1.8.0
(function() {
  var StormService, fs, merge, zebraService,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StormService = require('stormservice');

  merge = require('fmerge');

  fs = require('fs');

  zebraService = (function(_super) {
    __extends(zebraService, _super);

    zebraService.prototype.schema = {
      name: "zebra",
      type: "object",
      additionalProperties: true,
      properties: {
        hostname: {
          "type": "string",
          "required": false
        },
        password: {
          "type": "string",
          "required": true
        },
        'enable password': {
          "type": "string",
          "required": false
        },
        'log file': {
          "type": "string",
          "required": false
        },
        interfaces: {
          name: "interfaces",
          type: "array",
          items: {
            name: "interface",
            type: "object",
            required: false,
            additionalProperties: true,
            properties: {
              description: {
                type: "string",
                required: false
              },
              'link-detect': {
                "type": "boolean",
                "required": false
              },
              'ip address': {
                "type": "string",
                "required": false
              }
            }
          }
        },
        'ip route': {
          "type": "string",
          "required": false
        },
        'ip forwarding': {
          "type": "boolean",
          "required": false
        },
        'ipv6 forwarding': {
          "type": "boolean",
          "required": false
        }
      }
    };

    zebraService.prototype.invocation = {
      name: 'zebra',
      path: '/sbin',
      monitor: true,
      args: [],
      options: {
        detached: true,
        stdio: ["ignore", -1, -1]
      }
    };

    function zebraService(id, data, opts) {
      if (data.instance != null) {
        this.instance = data.instance;
        delete data.instance;
      }
      if (opts == null) {
        opts = {};
      }
      if (opts.configPath == null) {
        opts.configPath = "/var/stormflash/plugins/quagga";
      }
      if (opts.logPath == null) {
        opts.logPath = "/var/log/zebra";
      }
      zebraService.__super__.constructor.call(this, id, data, opts);
      this.configs = {
        service: {
          filename: "" + this.configPath + "/zebra_" + this.id + ".conf"
        }
      };
      this.invocation = merge(this.invocation, {
        args: ["--config_file", "" + this.configs.service.filename, "-d"],
        options: {
          stdio: ["ignore", this.out, this.err]
        }
      });
      this.configs.service.generator = (function(_this) {
        return function(callback) {
          var key, keyy, obj, val, value, zebraconfig, _i, _len, _ref;
          zebraconfig = '';
          _ref = _this.data;
          for (key in _ref) {
            val = _ref[key];
            switch (typeof val) {
              case "object":
                for (_i = 0, _len = val.length; _i < _len; _i++) {
                  obj = val[_i];
                  console.log("obj is " + obj);
                  for (keyy in obj) {
                    value = obj[keyy];
                    console.log("keyy , value " + keyy);
                    zebraconfig += keyy + ' ' + value + "\n";
                  }
                }
                break;
              case "number":
              case "string":
                zebraconfig += key + ' ' + val + "\n";
                break;
              case "boolean":
                zebraconfig += key + "\n";
            }
          }
          return callback(zebraconfig);
        };
      })(this);
    }

    zebraService.prototype.getconfig = function() {
      return this.configs;
    };

    zebraService.prototype.getinvocation = function() {
      return this.invocation;
    };

    zebraService.prototype.destructor = function() {
      return this.eliminate();
    };

    return zebraService;

  })(StormService);

  module.exports = zebraService;

}).call(this);
